# Setup
title:               Horizon
tagline:             'Life, product and other things'
description:         'I make digital products that solve a problem and delight users, social impact is a plus!'
url:                 https://asaiat.in
baseurl:             '' 
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Shobhit asai
  url:               https://twitter.com/asaiatin
  email:             asaiatin@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-gist
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
# Custom vars
version:             1.1.0
google_analytics_id: G-EH6JMJ3MQE
